#---------------------------------#
#      general configuration      #
#---------------------------------#

version: "{build}"

#---------------------------------#
#     artifacts configuration     #
#---------------------------------#

artifacts:
  - path: 'Vtex.RabbitMQ.*.nupkg'
    name: nuget

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2015

environment:
  nodejs_version: "0.12"

init:
  - git config --global core.autocrlf true

cache:
  - packages -> **\packages.config
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i gulp -g
  - npm i
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - gulp build
  - "if [%appveyor_repo_tag%] == [true] gulp pack"

#---------------------------------#
#       test configuration        #
#---------------------------------#

test: off
#before_test:
#  - gulp check-await

#test_script:
#  - gulp test

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: Environment
    name: NuGet
    artifact: nuget
    on:
      appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Slack
    auth_token:
      secure: ZWnYwYbU2wQBnhev4Yfg66sfznyXPtlIYCxrKIVedkw1fCAdJDbdYDu6k9BjIfuS
    channel: portal
